### PR TITLE
Make input and output scrollable instead of the page itself

### PR DESCRIPTION
**Pull request by SierraKomodo**
I hate CSS.

You can now scroll up and down in the input and output boxes without scrolling the entire viewport.

### CODE REVIEW

**Comment by Dibasic** [comment]
This would be great. Right now it breaks a few things:

top left corner, `fieldset` and `#input` no longer share a left edge:
before: 
image
after: 
image

bottom center, `#input` and `#output` no longer share a bottom edge:
before: 
image
after: 
image

top right corner, `fieldset` border no longer stops at page: 
before: 
image
after: 
image

**Comment by SierraKomodo** [comment]
Because of CSS being absolutely stupid, I had to shrink the width of the wrapper and center-align so that the scrollbars wouldn't extend off-screen. If you can find a better way to make that work, please do, because I'm at a loss for that one :(

As for the fieldset border... I can't figure that out at all. Nothing I change seems to be affecting that at all.

**Comment by soryy708** [comment]
Here's an alternative PR that achieves the same thing: https://github.com/Dibasic/SS13PaperworkSimulator/pull/15

**Comment by soryy708** [comment]
@SierraKomodo Your issue sounds like it should be fixed by `box-sizing: border-box`

**Comment by Dibasic** [comment]
@SierraKomodo Thanks, looks like someone beat you to it. Closing for now as #15 handles this.

**Pull request closed without merging**
