### PR TITLE
Implement dark themes

### PR DESCRIPTION
**Pull request by soryy708**
image

### CODE REVIEW

**Comment by soryy708** [comment]
@Dibasic Any issues?

**Review by Dibasic — COMMENTED** [review]
This works as advertised.

However, white on black isn't the easiest on the eyes. I'd suggest finding some greys and sticking those in or using something that already exists like Solarized.

Solarized would be something like
input and output backgrounds: 002B36
page background, UI highlight backgrounds: 073642
text and icons: 839496
all italic text: 586E75
all header and bold text, all borders and bullets: 93A1A1

**Comment by Dibasic** [comment]
Would CSS custom properties be a better implementation than a `dark.css` file? That would make adding more themes much easier.

CSS custom properties for colors and a few other tweaks (like making sure border-radii are in main.css instead of inheriting from jQuery UI) could also allow us to ditch the themerolled version of jQuery UI.

**Comment by soryy708** [comment]
@Dibasic You want to decouple the various styles, while keeping things portable/backwards-compatible. Separate style file is the way to go.
It can be refactor further if we set up Sass in the build process (think: variables)

**Comment by soryy708** [comment]
image

**Review by Dibasic — CHANGES_REQUESTED** [review]
That's fair.

I notice a few minor issues:

- The starting min-width of the settings menu is narrow enough to force text to wrap. Could we force no wrapping and/or increase the min-width?

- The new UI theme option in the settings menu doesn't line up with the other settings' text, because there is no checkbox in front of it. Could we have the text line up and/or push either the checkboxes to the right side or the select to the left side?

- The animation on the control buttons causes them to still have their old background for whatever the delay is (300ms I believe). This makes it look like they flash when the theme is changed. Could we just take off the delay or make it very short if it's there to prevent tooltip flickering?

**Comment by soryy708** [comment]
* The 1st bullet is irrelevant to this PR.
* The 2nd bullet is bollocks. 
* The 3rd bullet is bollocks. It's no big deal, and the solution would be too convoluted.

**Comment by Dibasic** [comment]
The first two aren't specific to this PR, I'll open issues for them when I merge this and get around to them later. 

Taking the 0.3s transitions out of `main.css` solves the problem in the third bullet point. Are those there to fix an issue or just for looks? It doesn't seem to cause any tooltip fighting, which is what I assumed they were introduced to prevent.

**Comment by soryy708** [comment]
They're for looks. If you insist, I'll cook something up.

**Comment by Dibasic** [comment]
They look nice, but flashing when the theme changes doesn't.

Thanks, newest commit works great, will merge in a moment.

**Comment by Dibasic** [comment]
Close #56

**Comment by soryy708** [comment]
@Dibasic There's a newer commit. Check that out.

**Review by Dibasic — APPROVED** [review]

**Pull request merged**
