### PR TITLE
Change scroll behaviour, responsivefy to narrow screens, and refactor CSS

### PR DESCRIPTION
**Pull request by soryy708**

### CODE REVIEW

**Comment by soryy708** [comment]
@Dibasic Which changes are requested?

**Comment by Dibasic** [comment]
The top right isn't lining up:

with scrollbar:
image

without scrollbar:
image

(Firefox and Edge)

Do you see a way to get it to share an edge with `fieldset`?

**Comment by soryy708** [comment]
Oh, good catch. Processing...

**Comment by soryy708** [comment]
@Dibasic Is this better now?

**Comment by soryy708** [comment]
I made the two halves become full-width when the screen's too narrow. Check it out.

**Comment by Dibasic** [comment]
It's definitely better, but still a 3px off for me in Firefox and Edge.

`#wrapper { width: calc(100% + 3px) }` makes the borders line up for me, but does a better way stand out to you?

edit: That was 3c5894, will check out this version

**Comment by soryy708** [comment]
I think it might be because `.panel` has `2px` padding. Maybe reduce `#menu` width by `2px` on the right? I'll try that. Buuuut.... Are you really looking for pixel-perfect?

**Comment by Dibasic** [comment]
No, I'll go ahead if we can't get them to line up, it just looks better if the borders match.

I like this way of handling a smaller screen. The `fieldset div.controlgroup` starts to overflow and looks weird, but that's an easy fix so don't worry about it for now.

**Comment by soryy708** [comment]
@Dibasic I fixed the alignment, and the controlgroup.

**Comment by Dibasic** [comment]
Working great now, thanks.

**Pull request merged**
